app:
  target_posts_per_day: 3
  burst_window_minutes: 90
  random_delay_sec: [15, 120]
  locale: ko_KR
  timezone: Asia/Seoul

cost:
  monthly_cap_usd: 20.0
  daily_cap_usd: 0.67

posting:
  mode: draft   # draft | public
  default_category_no: 0
  hashtags: ["리뷰", "쇼핑", "추천"]
  roundup:
    list_post_items_min: 3
    list_post_items_max: 7
  link_policy:
    per_product_max: 1
    final_cta_button: true
    dedupe_same_url: "prefer_button"

moderation:
  banned_categories: ["의약품", "성인용품", "주류", "니코틴", "의료기기"]
  fact_check:
    price_tolerance_pct: 5
    mandatory_fields: ["모델명", "주요스펙", "구성품"]

storage:
  url: sqlite:///app.db
  # example for Postgres: postgresql+psycopg://user:pass@localhost:5432/cpp
  echo: false

providers:
  openai:
    model: gpt-4o-mini

coupang_source:
  mode: crawler  # crawler | api | auto (default)

keywords:
  daily_count: 3
  # Optional: seed categories used by the keyword generator prompt
  seed_categories: ["가전", "주방", "리빙", "디지털"]
  # Optional hard fallback list when LLM is unavailable
  fallback_list: ["가습기", "제습기", "무선 청소기", "에어프라이어", "전기포트"]

crawler:
  retries: 3
  connect_timeout: 8
  read_timeout: 25
  mobile_first: true

affiliate:
  generation: none            # none | partners_api | portal (beta)
  require_for_publish: true   # true면 제휴링크 없으면 게시 스킵
